//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quize
    {
        public Quize()
        {
            this.Questions = new HashSet<Question>();
            this.QuizResults = new HashSet<QuizResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Detail { get; set; }
        public string Icon { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> PassingMarks { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<QuizResult> QuizResults { get; set; }
    }
}
