//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuizResult
    {
        public int Id { get; set; }
        public Nullable<int> QuizId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Attempt { get; set; }
        public Nullable<int> QuizMarks { get; set; }
        public Nullable<int> ObtainedMarks { get; set; }
        public Nullable<bool> IsPass { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
    
        public virtual Quize Quize { get; set; }
        public virtual QuizResultDetail QuizResultDetail { get; set; }
        public virtual User User { get; set; }
    }
}
