//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyQuizApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Quizes = new HashSet<Quize>();
            this.QuizResults = new HashSet<QuizResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> UserTypeId { get; set; }
    
        public virtual ICollection<Quize> Quizes { get; set; }
        public virtual ICollection<QuizResult> QuizResults { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
